### ISSUE TITLE
关于npm 上传脚本

### ISSUE THREAD

**Issue by SonicMiso** [Lionad-Morotar/blog#20]
package.json里的 **"upload": "sftp -P 26160 root@45.78.54.181 && lcd dist && put -r ./ /var/www/html"** 这个脚本好像不能连贯执行啊，进了sftp 以后不会执行后面的 lcd 和put， 只有手动输入exit 退出sftp 后才开始执行后面这俩命令

**Comment by Lionad-Morotar** [comment]
是的。其实我只是把它放在那里做个备忘用，因为我很少重编译并上传。如果你的博客经常更新的话，可以尝试用 netlify 或者 Github Action 做自动部署，或者写个 NodeJS 脚本用来上传。
